//! MVP layout #1 — "I just cloned this repo, what is it?" (NEW_ROADMAP Phase 2.a).

use anyhow::Result;

use super::{Layout, OutputFile};
use crate::config::Config;
use crate::ir::CodeModel;
use crate::render::markdown::MarkdownBuilder;

/// Layout targeting a developer who just ran `git clone`.
#[derive(Default)]
pub struct ProjectOverviewLayout;

impl Layout for ProjectOverviewLayout {
    fn name(&self) -> &'static str {
        "project-overview"
    }

    fn render(&self, model: &CodeModel, config: &Config) -> Result<Vec<OutputFile>> {
        let mut md = MarkdownBuilder::new();

        // TODO(Phase 2.a): replace this skeleton with the real sections:
        //   - Project summary (derive from top-level doc comment / README)
        //   - Module table: module | purpose | key symbols
        //   - Dependency diagram (Mermaid) built from `model.edges`
        //   - Data-flow narrative traced from auto-detected entrypoints
        //   - Quick-start dev guide
        //   - "Key files" section
        md.heading(1, "Project Overview")
            .paragraph("Generated by CodeTwin — `project-overview` layout.")
            .heading(2, "Modules")
            .paragraph(&format!(
                "{} module(s), {} edge(s), language: `{}`",
                model.modules.len(),
                model.edges.len(),
                model.language
            ));

        Ok(vec![OutputFile {
            path: config.output_file.clone(),
            content: md.finish(),
            format: config.format,
        }])
    }
}
