//! MVP layout #2 — "I'm reviewing this system" (NEW_ROADMAP Phase 2.b).

use anyhow::Result;

use super::{Layout, OutputFile};
use crate::config::Config;
use crate::ir::CodeModel;
use crate::render::markdown::MarkdownBuilder;

/// Architecture-map layout for architects and tech leads.
#[derive(Default)]
pub struct ArchitectureMapLayout;

impl Layout for ArchitectureMapLayout {
    fn name(&self) -> &'static str {
        "architecture-map"
    }

    fn render(&self, model: &CodeModel, config: &Config) -> Result<Vec<OutputFile>> {
        let mut md = MarkdownBuilder::new();

        // TODO(Phase 2.b): flesh out the sections:
        //   - High-level system diagram (Mermaid)
        //   - Layer breakdown with inter-layer dependency arrows
        //   - Module detail per layer (types, functions, visibility)
        //   - Coupling metrics (fan-in / fan-out per module)
        //   - Circular-dependency warnings (use `petgraph::algo::tarjan_scc`)
        md.heading(1, "Architecture Map")
            .paragraph("Generated by CodeTwin — `architecture-map` layout.")
            .heading(2, "Layers")
            .paragraph(&format!(
                "{} declared layer(s); auto-detection TODO(Phase 2.b).",
                config.layers.len()
            ));

        let _ = model; // Suppress unused warning until implemented.

        Ok(vec![OutputFile {
            path: config.output_file.clone(),
            content: md.finish(),
            format: config.format,
        }])
    }
}
